print("shaxmat doskasidai kordinatani kiriting \n ruh kordinatasi : ")
x = int(input("x : "))
y = int(input("y : "))
print("ruh o'tishi kerak bo'lgan kordinata : ")
x1 = int(input("x1 : "))
y1 = int(input("y1 : "))
print("ruh [",x,y,"] kordinatadan [",x1,y1,"] kordinataga  o'ta oladi : ",(x==x1 and y!=y1)or(x!=x1 and y==y1))
