print("shaxmat doskasidai kordinatani kiriting \n fil kordinatasi : ")
x = int(input("x : "))
y = int(input("y : "))
print("fil o'tishi kerak bo'lgan kordinata : ")
x1 = int(input("x1 : "))
y1 = int(input("y1 : "))
print("fil [",x,y,"] kordinatadan [",x1,y1,"] kordinataga  o'ta oladi : ",(x-x1==y-y1))
