print("(x,y) nuqtalarni kiriting : ")
x = int(input("x : "))
y = int(input("y : "))
print("(x1,y1) nuqtalarni kiriting : ")
x1 = int(input("x1 : "))
y1 = int(input("y1 : "))
print("(x2,y2) nuqtalarni kiriting : ")
x2 = int(input("x2 : "))
y2 = int(input("y2 : "))
bol = (x < x1 and y < y1) and (x > x2 and y > y2)
print("shart bajarildi : ",bol)
