print("Вводите кордината 2 точками")
print("1-nuqta")
x1 = int(input("x1 : "))
y1 = int(input("y1 : "))
print("2-nuqta")
x2 = int(input("x2 : "))
y2 = int(input("y2 : "))
masofa = pow(pow((x2-x1),2)+pow((y2-y1),2),1/2)
print("расстояние : ",masofa)
