print("Вводите координаты трех вершин треугольника")
print("1-вершин ")
x1 = int(input("x1 : "))
y1 = int(input("y1 : "))
print("2-вершин ")
x2 = int(input("x2 : "))
y2 = int(input("y2 : "))
print("3-вершин ")
x3 = int(input("x3 : "))
y3 = int(input("y3 : "))
a = pow(pow((x2-x1),2)+pow((y2-y1),2),1/2)
b = pow(pow((x3-x1),2)+pow((y3-y1),2),1/2)
c = pow(pow((x3-x2),2)+pow((y3-y2),2),1/2)
p = a+b+c
s = pow((p * (p-a)*(p-b)*(p-c)),1/2)
print("Площадь : ",s ,"\n Периметр : ",p)
